stages:
  - validate

variables:
  GIT_STRATEGY: clone
  
before_script:
  - node -v
  - npm -v

build-check:
  stage: validate
  script:
    - echo "Проверка сборки проекта"
    - npm install
    - npm run build

lint-check:
  stage: validate
  script:
    - echo "Проверка синтаксических ошибок линтером"
    - cd backend
    - npm install
    - npx eslint .