stages:
  - validate

variables:
  GIT_STRATEGY: clone

before_script:
  - node -v
  - npm -v

build-check-frontend:
  stage: validate
  script:
    - echo "=== Проверка сборки frontend ==="
    - cd frontend
    - npm install
    - npm run build

build-check-backend:
  stage: validate
  script:
    - echo "=== Проверка backend ==="
    - cd backend
    - npm install

lint-check-backend:
  stage: validate
  script:
    - echo "=== Проверка линтером backend ==="
    - cd backend
    - npm install
    - npx eslint .

test-backend:
  stage: validate
  script:
    - echo "=== Запуск тестов backend ==="
    - cd backend
    - npm install
    - npm test

run-backend:
  stage: validate
  script:
    - echo "=== Проверка запуска backend ==="
    - cd backend
    - npm install
    - node index.js & sleep 5

    